= s_mach.www: Web hosting files for s_mach.net
Lance Gatlin <lance.gatlin@gmail.com>
v1,20-Feb-2015
:blogpost-status: unpublished
:blogpost-categories: s_mach, scala

*UNDER CONSTRUCTION*

== Overview
This repository contains all of the files (HTML, CSS, Javascript, Scala, etc)
necessary for hosting the web site http://s_mach.net


The static view of this site can be viewed
link:http://s-mach.github.io/s_mach.www/[here]


.Goals of this repository:
* Promote continuous improvement in S-Mach code product through attracting the
highest level of critique
* Demonstrate current technical capabilities of S-Mach
* Provide educational resource for how-to's and lessons learned

.Design goals of this website:
* link:http://en.wikipedia.org/wiki/Responsive_web_design[Responsive web design]
* link:http://designshack.net/articles/css/mobilefirst/[Mobile-first web design]
* link:http://en.wikipedia.org/wiki/Unobtrusive_JavaScript[Unobtrusive Javascript]

Many thanks to S-Mach's art designer http://silverrost.com!

== License

The contents of this repository are licensed under the Creative Commons
Attribution-NonCommercial-NoDerivatives 4.0 License
(http://creativecommons.org/licenses/by-nc-nd/4.0/legalcode). The files here are
released for educational purposes only. Many files contain links to remote
images that are the copyrighted material of S-Mach, Inc. All rights are reserved
for their exclusive use by S-Mach, Inc.
