package cdn

package object assets {
  object NavShadow extends Asset
  object HorizDivider extends Asset
  object Cloud1 extends Asset
  object Cloud2 extends Asset
  object Recruit extends Asset
  object Ribbon extends Asset
  object Train extends Asset
  object Place extends Asset
  object CleavedCircleButton extends Asset
  object WhyScala extends Asset
  object ChooseTheBestBlank extends Asset
  object ChooseTheBest extends Asset
  object BlogExample1 extends Asset
  object BlogExample2 extends Asset
  object BlogExample3 extends Asset
  object CustomerExample1 extends Asset
  object CustomerExample2 extends Asset
  object CustomerExample3 extends Asset
  object CustomerExample4 extends Asset
  object CustomerExample5 extends Asset
  object CustomerExample6 extends Asset
  object FooterLogo extends Asset
  object ButtonToTop extends Asset
  object ScalaMachine extends Asset
  object TrainingPlan extends Asset
  object WeRecruitHorizontal extends Asset
  object WeRecruitVertical extends Asset
  object Mentor extends Asset
  object WhiteBkgRibbon extends Asset
  object WhiteBkgTrain extends Asset
  object Certify extends Asset
  object YouInterviewThem extends Asset
  object WePlace extends Asset
  object SMachLogo extends Asset
  object Separator extends Asset
  object EmailIcon extends Asset
  object TelephoneIcon extends Asset
  object GithubIcon extends Asset
}
